### ISSUE TITLE
Documentation checklist

### ISSUE THREAD

**Issue by SaFrMo** [breakfast-studio/lunchboxjs#12]
- [x] Installation
- [x] Lunchbox wrapper
- [x] Component events
- [x] Extending
- [x] #9 
- [x] Camera
    - [x] Position (Lunchbox prop)
    - [x] Look/LookAt (Lunchbox prop)
- [x] Lunchbox wrapper props
- [x] onStart
- [x] camera
- [x] scene
- [x] renderer
- [x] Custom scenes
- [x] Custom cameras
- [x] Custom renderers
